# Spring properties
spring:
  application:
    name: CaasDashboard  # Identify this application
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


##INFRA_ADMIN Settings
project:
  name: paasta-caas-dashboard
  artifactId: paasta-caas-dashboard
  description: paasta-caas-dashboard
info:
  app:
    encoding: Encoding - UTF-8
  java:
    source: Source - java ver
    target: Instance1 - Java ver
  spring:
    profiles: ${spring.profiles.active:default}
  build:
    name: ${project.name}
    artifact: ${project.artifactId}
    description: ${project.description}


management:
  security:
    enabled: false

# HTTP Server
server:
  port: ${PORT:8091}   # HTTP (Tomcat) port

---
spring:
  profiles: local

cf:
  uaa:
    oauth:
      info:
        uri: https://uaa.115.68.46.187.xip.io/userinfo
      token:
        check:
          uri: https://uaa.115.68.46.187.xip.io/check_token
        access:
          uri: https://uaa.115.68.46.187.xip.io/oauth/token
      logout:
        url: https://uaa.115.68.46.187.xip.io/logout
      authorization:
        uri: https://uaa.115.68.46.187.xip.io/oauth/authorize
      client:
        id: caasclient
        secret: clientsecret
  api:
    url: https://api.115.68.46.187.xip.io

---
spring:
  profiles: dev
